# -*- mode: ruby -*-
# vi: set ft=ruby :

class String
  def black;          "\e[30m#{self}\e[0m" end
  def red;            "\e[31m#{self}\e[0m" end
  def green;          "\e[32m#{self}\e[0m" end
  def brown;          "\e[33m#{self}\e[0m" end
  def blue;           "\e[34m#{self}\e[0m" end
  def magenta;        "\e[35m#{self}\e[0m" end
  def cyan;           "\e[36m#{self}\e[0m" end
  def gray;           "\e[37m#{self}\e[0m" end
  
  def bg_black;       "\e[40m#{self}\e[0m" end
  def bg_red;         "\e[41m#{self}\e[0m" end
  def bg_green;       "\e[42m#{self}\e[0m" end
  def bg_brown;       "\e[43m#{self}\e[0m" end
  def bg_blue;        "\e[44m#{self}\e[0m" end
  def bg_magenta;     "\e[45m#{self}\e[0m" end
  def bg_cyan;        "\e[46m#{self}\e[0m" end
  def bg_gray;        "\e[47m#{self}\e[0m" end
  
  def bold;           "\e[1m#{self}\e[22m" end
  def italic;         "\e[3m#{self}\e[23m" end
  def underline;      "\e[4m#{self}\e[24m" end
  def blink;          "\e[5m#{self}\e[25m" end
  def reverse_color;  "\e[7m#{self}\e[27m" end
end

VAGRANTFILE_API_VERSION = "2"
VAGRANT_ROOT = File.dirname( File.expand_path( __FILE__ ) )

Vagrant.configure( VAGRANTFILE_API_VERSION ) do |config|

  os_type        = 'windows'

  if ( RUBY_PLATFORM.include? 'darwin' )
    os_type = 'macos'
  elsif ( /cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM ) == nil
    os_type = '*nix'
  end

  box_name                = 'bento/ubuntu-18.04'
  environment_name        = 'NextData2020'
  ip_address              = '192.168.33.10'

  config.vm.box     = box_name
  config.vm.define environment_name do |t|
  end

  config.vm.network "private_network", ip: ip_address

  config.vm.provider "virtualbox" do |vb|
    vb.gui    = false
    vb.memory = "2048"
    vb.cpus   = 2
    vb.name   = environment_name
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update && apt upgrade -y && apt autoremove -y
    #apt install -y zsh git wget
    #wget --no-check-certificate https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | sh 
    #chsh -s /bin/zsh vagrant
    #sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="3den"/g' ~/.zshrc
  SHELL

  #config.vm.provision "docker",
  #  images: [ "mysql:8.0.19" ]

  config.vm.provision "docker" do |d|
    d.run "mysql:5.7.29",
      args: "--name mysql -e MYSQL_ROOT_PASSWORD=password --detach --publish 3306:3306"
  end

  if ARGV[0] == "up" or ARGV[0] == "reload" or ARGV[0] == "status"
    print "\n"

    puts "Ruby Platform       : " + "#{RUBY_PLATFORM}".green + "\n"
    puts "OS Type             : " + "#{os_type}".green + "\n"
    puts "Vagrant API Version : " + "#{VAGRANTFILE_API_VERSION}".green + "\n"
    puts "Environment Name    : " + "#{environment_name}".green + "\n"
    puts "Ip Address          : " + "#{ip_address}".bold.reverse_color.green + "\n"
    puts "Box Name            : " + "#{box_name}".green + "\n"

    print "\n"
  end

end
